apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubefoundry-kaito-provider-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubefoundry-kaito-provider-role
subjects:
- kind: ServiceAccount
  name: kubefoundry-kaito-provider
  namespace: kubefoundry-system
