---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kubefoundry.kubefoundry.ai
  resources:
  - inferenceproviderconfigs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubefoundry.kubefoundry.ai
  resources:
  - inferenceproviderconfigs/status
  - modeldeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kubefoundry.kubefoundry.ai
  resources:
  - modeldeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubefoundry.kubefoundry.ai
  resources:
  - modeldeployments/finalizers
  verbs:
  - update
- apiGroups:
  - nvidia.com
  resources:
  - dynamographdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
