apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeairunway-kuberay-provider-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeairunway-kuberay-provider-role
subjects:
- kind: ServiceAccount
  name: kubeairunway-kuberay-provider
  namespace: kubeairunway-system
